%% Plot TFEB Experiments

clear all, close all, clc
warning off

%% Initialization

expNAME = {'Fig4-5A_HBSSPulses','Fig4-5B_HBSSStep','Fig4-8A_HBSS+BafA1Pulses',...
    'Fig4-8B_HBSS+Torin1Pulses','Fig4-9A_HBSS+CHXPulses','Fig4-9B_HBSS+BortPulses'...
    'Fig4-10A_Torin1@300nMPulses','Fig4-10B_Torin1@300nMStep',...
    'Fig4-10C_Torin1@300nMVariablePulses','Fig4-10D_Torin1@1uMSinglePulseTorin',...
    'Fig4-11A_Torin1@1uM+CHXPulses','Fig4-11B_Torin1@1uM+BortPulses',...
    'Fig4-11C_Torin1@1uM+CHXVariablePulses','Fig4-11D_Torin1@1uM+BortVariablePulses',...
    'Fig4-12A_AZD8055Pulses','Fig4-12B_AZD8055+BortPulses','FigA-3A_Torin@50nMPulses',...
    'FigA-3B_Torin@1uMStep','FigA-4_Torin@300nMNoFirstPulse'};

inputLABEL = {'Input','Input','Input (+BafA1)','Input','Input (+CHX)',...
    'Input (+Bort)','Input','Input','Input','Input','Input (+CHX)',...
    'Input (+Bort)','Input (+CHX)','Input (+Bort)','Input','Input (+Bort)',...
    'Input','Input','Input'};

inputTICK = {{'RPMI','HBSS'},{'RPMI','HBSS'},{'RPMI','HBSS'},{'RPMI','HBSS+T1'},...
    {'RPMI','HBSS'},{'RPMI','HBSS'},{'-Torin1','+Torin1'},{'-Torin1','+Torin1'},...
    {'-Torin1','+Torin1'},{'-Torin1','+Torin1'},{'-Torin1','+Torin1'},...
    {'-Torin1','+Torin1'},{'-Torin1','+Torin1'},{'-Torin1','+Torin1'},...
    {'-AZD8055','+AZD8055'},{'-AZD8055','+AZD8055'},{'-Torin1','+Torin1'},...
    {'-Torin1','+Torin1'},{'-Torin1','+Torin1'}};

%% Cycle

for esp = 1:length(expNAME)
    
    disp(strcat('Exp N° ',num2str(esp),'/',num2str(length(expNAME)),': ',expNAME{esp}))

    makeFig(expNAME{esp},inputLABEL{esp},inputTICK{esp});
    
end